### ISSUE TITLE
A better way to upgrade?

### ISSUE THREAD

**Issue by till** [knadh/listmonk#1057]
Hey,

I was wondering if there is better way to upgrade listmonk in "non interactive" environments. So for example, I run listmonk on a Docker Swarm and try to avoid ssh'ing into the cluster if possible. But I feel even in a Kubernetes with an `initContainer`, this might be a little struggle.

Right now, I am starting listmonk like so:

```yaml
version: "3.7"
  listmonkdb:
    image: postgres:13
    // ...

  listmonk:
    image: image:version
    command: sh -c "./listmonk --install --idempotent --yes; ./listmonk"
    environment:
      LISTMONK_app__address: "0.0.0.0:9000"
      LISTMONK_app__admin_username: admin
      LISTMONK_app__admin_password: "redacted"
      LISTMONK_db__host: tasks.listmonkdb
      LISTMONK_db__port: 5432
      LISTMONK_db__user: listmonkdbo
      LISTMONK_db__password: "${POSTGRES_PASSWORD}"
      LISTMONK_db__database: listmonk
      LISTMONK_db__ssl_mode: "disable"
      TZ: Etc/UTC
    deploy:
      placement:
        constraints:
          - "node.role==worker"
      update_config:
        failure_action: rollback
        order: start-first
```

When I upgrade listmonk, I have to adjust the image and that usually leads to restarts. The last log message is that the database migrations need to be applied, on repeat. Then I adjust command of the service as a one off:

```
    command: sh -c "./listmonk --upgrade --yes; ./listmonk --install --idempotent --yes; ./listmonk"
```

This works, but it seems not ideal. I've been also wondering if I just keep the command as is, or if there is a negative side effect (except for upgrade the database without doing a backup first).

IMHO, it could be an improvement if the service wouldn't crash/restart and it would allow entering the running container to execute `./listmonk --upgrade`.

But otherwise, I wanted to open this ticket to see what other things people have done. I've been also wondering if it's possible to adjust the entrypoint completely and have something like (pseudo code):

```bash
#!/bin/bash
needs_upgrade() {
  local check =$(./listmonk --needs-upgrade)
  echo $check
}

if [ needs_upgrade() == "yes" ]; then
  ./listmonk --upgrade --yes
fi

./listmonk --install --idempotent --yes
./listmonk
```
