### ISSUE TITLE
"Powered by" is not translated when using local static directory

### ISSUE THREAD

**Issue by mvthde** [knadh/listmonk#1233]
**Version:**
 - listmonk: 2.3.0 (Docker)
 - OS: Debian 11

**Description of the bug and steps to reproduce:**
I am using listmonk with Docker and copied the [static](https://github.com/knadh/listmonk/tree/master/static) directory locally, so I can customize the system email templates ([Docs](https://listmonk.app/docs/templating/#system-templates)). Directly after switching to local static files, the "Powered by" label is not being translated anymore (e.g. in emails and the public index.html template). It seems that `{{ L.T "public.poweredBy" }}` is not replaced correcty.

docker-compose.yml
```
version: "3.7"

services:
  db:
    image: postgres:13
    ports:
      - "127.0.0.1:9432:5432"
    networks:
      - listmonk
    environment:
      - POSTGRES_PASSWORD=listmonk
      - POSTGRES_USER=listmonk
      - POSTGRES_DB=listmonk
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U listmonk"]
      interval: 10s
      timeout: 5s
      retries: 6
    container_name: listmonk_db
    volumes:
      - ./data/database:/var/lib/postgresql/data

  app:
    restart: unless-stopped
    image: listmonk/listmonk:latest
    ports:
      - "127.0.0.1:9000:9000"
    networks:
      - listmonk
    environment:
      - TZ=Europe/Berlin
    container_name: listmonk
    depends_on:
      - db
    command: "./listmonk --static-dir=/listmonk/static"
    volumes:
      - ./data/config.toml:/listmonk/config.toml
      - ./data/static:/listmonk/static
      - ./data/uploads:/listmonk/uploads

networks:
  listmonk:
```

**Screenshots:**
German:
![listmonk_de](https://user-images.githubusercontent.com/86915613/223807105-2b008062-d543-4100-b307-ad6207f79741.png)

English:
![listmonk_en](https://user-images.githubusercontent.com/86915613/223807109-dc30f0b0-978c-4b1c-91a0-f497d820e1a1.png)
