### ISSUE TITLE
Errors in Listmonk swagger API spec. (see  https://listmonk.app/docs/swagger/collections.yaml )

### ISSUE THREAD

**Issue by stargazer33** [knadh/listmonk#1308]
**Version:**
latest, see https://listmonk.app/docs/swagger/collections.yaml

**Description of the bug and steps to reproduce:**
I want to create a client for Listmonk API (Swagger).
So I use the [openapi-generator](https://openapi-generator.tech) to create the client code in my programming language.
As part of code generation process this tool VALIDATES the API specification

There are errors during valudation process, see below.
This tool (openapi-generator) found 6 errors in the Listmonk API 
I think, this should be fixed

***Steps to reproduce:***
1. Check your Java version (and install Java if necessary).
We need Java 1.8.X or more
```
$ java -version
java version "1.8.0_151"
...
```

2. Download the openapi-generator CLI as in documentation  https://openapi-generator.tech/docs/installation/#jar
```
wget https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/6.5.0/openapi-generator-cli-6.5.0.jar -O openapi-generator-cli.jar
```

3. Run the openapi-generator "validate" command:
```
java -jar openapi-generator-cli.jar validate -i https://listmonk.app/docs/swagger/collections.yaml
```

**Screenshots:**
```
$ java -jar openapi-generator-cli.jar validate -i https://listmonk.app/docs/swagger/collections.yaml 
Validating spec (https://listmonk.app/docs/swagger/collections.yaml)
Errors:
	- attribute
	  paths.'/subscribers/{id}/bounces'(get).responses.200.content.'application/json'.schema.items
	  is missing
	- paths.'/campaigns/{campaign_id}/text'. Declared path parameter campaign_id needs to be
	  defined as a path parameter in path or operation level
	- attribute paths.'/bounces'(get).responses.200.content.'application/json'.schema.items is
	  missing
	- paths.'/lists/{list_id}'. Declared path parameter list_id needs to be defined as a path
	  parameter in path or operation level
	- paths.'/media/{media_id}'. Declared path parameter media_id needs to be defined as a path
	  parameter in path or operation level
	- paths.'/bounces/{id}'. Declared path parameter id needs to be defined as a path parameter
	  in path or operation level

[error] Spec has 6 errors.
```

**Comment by knadh** [comment]
CC @rohansh-tty

**Comment by stargazer33** [comment]
UPDATE:

the   `/campaigns` description in the *.yml file is also not correct:
```
/campaigns:
    get:
      description: handles retrieval of campaigns
      parameters:
        - in: query
          name: page
          description: Page number for paginated results
          schema:
            type: integer
            format: int32
        - in: query
          name: per_page
          description: max number of records to return per page
          schema:
            type: integer
            format: int32
```
