### ISSUE TITLE
Parameter missing in swagger API spec. (see https://listmonk.app/docs/swagger/collections.yaml ) 

### ISSUE THREAD

**Issue by stargazer33** [knadh/listmonk#1313]
**Version:**
latest, see https://listmonk.app/docs/swagger/collections.yaml

The collections.yaml contains formal description of 
GET /subscribers
```
  /subscribers:
    get:
      tags:
        - Subscribers
      description: returns all subscribers.
      parameters:
        - in: query
          name: page
          description: number of records to skip
          schema:
            type: integer
            format: int32
        - in: query
          name: per_page
          description: max number of records to return per page
          schema:
            type: integer
            format: int32
```

**The collections.yaml missing the `query` parameter!**

Compare it with the documentation page providing example of GET /subscribers:
```
GET /api/subscribers
Gets subscribers with an SQL expression.

Example Request
curl -X GET 'http://localhost:9000/api/subscribers' \
    --url-query 'page=1' \
    --url-query 'per_page=100' \
    --url-query "query=subscribers.name LIKE 'Test%' AND subscribers.attribs->>'city' = 'Bengaluru'"

To skip pagination and retrieve all records, pass per_page=all.
```
