### ISSUE TITLE
Redundant "data" field in API spec (collections.yaml)

### ISSUE THREAD

**Issue by stargazer33** [knadh/listmonk#1321]
**Version:**
latest, see https://listmonk.app/docs/swagger/collections.yaml

After fixing https://github.com/knadh/listmonk/issues/1317 still there are problems in the *.yml file.

Now the `data` field added to JSON response (everywhere?). This is great.
What is not great - the `data` field **still** exists in some response objects/structures.
It looks like the response should contain the `data` two times, which is not the case!

I know about these places:

These two places: it is definetly a bug:
Line 3106 (in collections.yaml):
```
    Campaign:
      type: object
      properties:
        data:
          type: object
          properties:
```

Line 3168:
```
    NewCampaign:
      type: object
      properties:
        data:
```

These two places: I'm not sure, please compare with real JSON response/test:
Line 2751:
```
    Settings:
      type: object
      properties:
        data:
```

```
    Bounce:
      type: object
      properties:
        data:
```

***Some additional info***
Having collections.yaml is a great help, thanks to the authors! 
I'm using it to generate client API in Java (need this API to talk to Listmonk from my program. I'm using/creating subscribers, campaigns and lists, nothing else)

It seems, this API spec -I mean the *.yml file- is not used in development of Listmonk server/client code (otherwise these bugs would be fixed very quickly).
I would suggest to setup some (half)automated check to compare the API described in *.yml with real JSONs used on server/client side. 
Without such check - it is a never ending story, there always be bugs

There are tools for this, look here: https://openapi.tools/#description-validators
One of these tools, [vacuum ](https://quobix.com/vacuum) written in Go by the way :-)

**Comment by knadh** [comment]
@stargazer33 since you're able to spot these issues and you're familiar with the spec, would greatly appreciate it if you could send a PR with the fixes. Will save compared to time passing these on to @rohansh-tty who is the original contributor of the collection. Thanks!

**Comment by stargazer33** [comment]
> @stargazer33 since you're able to spot these issues ...

@knadh - I am focused only on small subset of Subscriber+List+Campaign calls, nothing else. 
I see these issues because I am writing code doing these API calls (using generated Java classes) and from time to time I discover these issues.

It should be a task of the original contributor to think how to fix ALL such issues (my suggestion - to setup automation)

**Comment by stargazer33** [comment]
One more problem:

I am doing this:
```
PUT /api/subscribers/lists
{
  "ids": 23,
  "action": "add",
  "target_list_ids": 12,
  "status": "unconfirmed"
}
```

and Listmonk response is:
```
400 Bad Request /api/subscribers/lists 
{
  "message": "One or more IDs are invalid: code=400, message=Unmarshal type error: expected=[]int, got=number, field=ids, offset=9, internal=json: cannot unmarshal number into Go struct field subQueryReq.ids of type []int"
}
```

**Comment by stargazer33** [comment]
And again one more:

The `Subscriber.id` field is sometimes `integer` and sometimes `number`
I have no idea which one is better, just make it consistent, I do not want to convert it on the client side.

Here it is integer: Line 473:
```
  "/subscribers/{id}/optin":
    post:
      description: sends an optin confirmation e-mail to a subscriber.
      tags:
        - Subscribers
      parameters:
        - in: path
          name: id
          required: true
          description: sends an optin confirmation e-mail to a subscriber
          schema:
            type: integer
```

Here it is number: Line 2940
```
    Subscriber:
      type: object
      properties:
        id:
          type: number
```
