### ISSUE TITLE
LISTMONK_db__host env variable not used on install

### ISSUE THREAD

**Issue by francoisromain** [knadh/listmonk#154]
Hello, 

this is a follow up question to this one: https://github.com/knadh/listmonk/issues/152

I have everything working fine when I configure the `config.toml` file. 
Instead, I would like to put the variables in the `.env` file. 

When I set `LISTMONK_db__host="db"` in the env file and run `docker-compose run --rm app ./listmonk --install`, it makes an error: 

```
2020/07/09 06:51:35 main.go:90: reading config: config.toml
2020/07/09 06:51:35 init.go:94: error connecting to DB: dial tcp: lookup demo-db on 127.0.0.11:53: no such host
```

what should I do to make this variable override `config.toml`? 

Thank you

**Comment by francoisromain** [comment]
I tried to expose the `.env` file inside the `app` container with a volume: 

```
    volumes:
      - ./.env:/listmonk/.env
```
it is not working yet

**Comment by mr-karan** [comment]
You need to specify `env_file` or `environment` key for it to work. Simply mounting a `.env` file has no effect on the process unless the variables are sourced.

Please read the docs for more info: https://docs.docker.com/compose/environment-variables/

**Comment by francoisromain** [comment]
Ok thank you 

I still can not get it to work :sweat_smile:

I replaced the `volumes` instruction with this: 

```
    env_file:
      - .env
```

The `.env` file has a `LISTMONK_db__host="db"` variable.

docker-compose up and then log into the `app` container. It says 

```
2020/07/09 08:57:03 main.go:90: reading config: config.toml
2020/07/09 08:57:03 init.go:94: error connecting to DB: dial tcp: lookup "db": no such host
```

here is my current setup: https://github.com/francoisromain/listmonk-nginx-proxy

Do you see where the problem is?

**Comment by francoisromain** [comment]
it works if I remove the quotes around vairables values in the `.env` file. I wonder how the arrays variables are going to work. testing now

**Comment by francoisromain** [comment]
Ok I have everything working now. Thank you very much for your time and fast responses (about docker related questions).

There are still a 2 things I don't understand: 

1. why quoted variables in `.env` don't work?

2. My installation work only with this default values in the `.env` file: 

```
LISTMONK_db__user=listmonk
LISTMONK_db__password=listmonk
```

if I change to 
```
LISTMONK_db__user=listmonk-anything
LISTMONK_db__password=listmonk-something
```

remove the listmonk-volume and install again, now it makes an error: 
```
2020/07/09 10:49:43 main.go:90: reading config: config.toml
2020/07/09 10:49:43 init.go:94: error connecting to DB: pq: password authentication failed for user "listmonk-anything"
```

here is the relevant parts of my `docker-compose.yml`: 

```
services:
  app:
    image: listmonk/listmonk:latest
    expose:
      - ${APP_PORT}
    depends_on:
      - db
    env_file:
      - .env
    restart: unless-stopped

  db:
    image: postgres:12
    environment:
      POSTGRES_DB: ${LISTMONK_db__database}
      POSTGRES_USER: ${LISTMONK_db__user}
      POSTGRES_PASSWORD: ${LISTMONK_db__password}
    restart: unless-stopped
    volumes:
      - type: volume
        source: listmonk-data
        target: /var/lib/postgresql/data
```

I close the issue. Still, I would be really intersted to have your advice about the two points above.
Thanks again.
