### ISSUE TITLE
Error on --static-dir if dir is empty

### ISSUE THREAD

**Issue by relikd** [knadh/listmonk#1599]
**Version:**
 - listmonk: v2.5.1
 - OS: alpine

**Description of the bug and steps to reproduce:**

`--static-dir` should either ignore missing directories, or create them on the fly.

Using the following docker-compose:

```yaml
app:
  command:
      - ./listmonk
      - --static-dir=./static
  volumes:
      - ./static:/listmonk/static
```

with an empty `static` dir will result in an error:

```log
failed reading static files from disk: './static': stat static/email-templates: no such file or directory
```

I dont need the other template dirs if I only want to overwrite the favicon or logo.svg.
As a workaround it suffices to re-create the directory structure.

PS. I think the [Templating Readme](https://listmonk.app/docs/templating/#public-pages) needs an update too.
`/static/public/` should be `/static/public/templates` ??
