### ISSUE TITLE
Lost data after restart container

### ISSUE THREAD

**Issue by smiell** [knadh/listmonk#1618]
**Version:**
 - listmonk: 2.5.1
 - OS: Ubuntu 20.04.3 LTS

**Description of the bug and steps to reproduce:**
Hello, I have problem with lost data e.g subscribers, listmonk configuration after app restart. It seems like after restart postgress will lost all your data form tables. 

After restart I only have demo data which are delivered with clean listmonk instalation. After data import I checked by comand line which data are saved to postgres by comand SELECT * FROM subscibers and I got all subscribers that I imported, but after restart container or whole docker service my data are disappering...

It's might be some bug. Could you check?

Here is docker compose file which I used to run listmonk:

```
version: "3.7"
services:
  db:
    image: postgres:13
    container_name: listmonk-db
    ports:
      - "5432:5432"
    networks:
      - listmonk
    environment:
      - POSTGRES_PASSWORD=listmonk
      - POSTGRES_USER=listmonk
      - POSTGRES_DB=listmonk
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U listmonk"]
      interval: 10s
      timeout: 5s
      retries: 6
    volumes:
      - /opt/listmonk/postgresql/:/var/lib/postgresql/data

  app:
    image: listmonk/listmonk:latest
    container_name: listmonk-web
    restart: always
    ports:
      - "9800:9000"
    command: [sh, -c, "yes | ./listmonk --install --config config.toml && ./listmonk --config config.toml"]
    networks:
      - listmonk
    environment:
      - TZ=Etc/UTC
    depends_on:
      - db
    volumes:
      - /opt/listmonk/config/config.toml:/listmonk/config.toml
      - /opt/listmonk/config/static:/listmonk/static

networks:
  listmonk:
```
I do not know what to do? Please help me with this

**Comment by smiell** [comment]
also here is my config.toml:
root@zenit:/opt/listmonk/config# cat config.toml
```
[app]
address = "0.0.0.0:9000"
admin_username = "xzihen"
admin_password = "Aligator12004!@"

# Database.
[db]
host = "listmonk-db"
port = 5432
user = "listmonk"
password = "listmonk"
database = "listmonk"
ssl_mode = "disable"
max_open = 25
max_idle = 25
max_lifetime = "300s"
```
Now I am looking for myabe my mistake with clearly reading instruction... Should I tell listmonk that is runing like production? Maybe now I am runing listmonk like something such demo...?

**Comment by knadh** [comment]
Sounds like an issue with Docker volume configuration. Please see this https://github.com/knadh/listmonk/issues/1089#issuecomment-1342492323

**Comment by smiell** [comment]
Okay, I made changes in my docker compose to:
```
  app:
    image: listmonk/listmonk:latest
    container_name: listmonk-web
    restart: always
    ports:
      - "9800:9000"
    command: [sh, -c, "yes | ./listmonk --config config.toml"]
    networks:
      - listmonk
    environment:
      - TZ=Etc/UTC
    depends_on:
      - db
    volumes:
      - /opt/listmonk/config/config.toml:/listmonk/config.toml
      - /opt/listmonk/config/static:/listmonk/static
```
I removed **--instal** from start comand. Now my data are presistent. Thank for help.
