### ISSUE TITLE
error starting HTTP server: listen tcp: address tcp/9000": unknown port

### ISSUE THREAD

**Issue by OtharSmirnow** [knadh/listmonk#1633]
Hi,
honestly I have no clue what is wrong.
Can you help?

**Version:**
 - listmonk: latest
 - OS: docker

**Description of the bug and steps to reproduce:**
HTTP server in app container does not start

**Logs etc**

1. no other containers are running
2. I followed instructions
3. compose file:
```
version: "3.7"

services:
  db:
    image: postgres:13-alpine
    container_name: listmonk_db
#    ports:
#      - "9432:5432"
    environment:
      - POSTGRES_PASSWORD=Attractor-Lifting1-Reminder
      - POSTGRES_USER=listmonk
      - POSTGRES_DB=listmonk
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U listmonk"]
      interval: 10s
      timeout: 5s
      retries: 6
    volumes:
      - type: volume
        source: listmonk-data
        target: /var/lib/postgresql/data
    networks:
      - listmonk

  app:
    restart: unless-stopped
    image: listmonk/listmonk:latest
    ports:
      - "8000:9000"
    networks:
      - listmonk
    environment:
      - LISTMONK_app__address="0.0.0.0:9000"
      - LISTMONK_app__admin_username=ListAdmin
      - LISTMONK_app__admin_password=Alias-Boned-Chubby3
      - LISTMONK_db__host=db
      - LISTMONK_db__port=5432
      - LISTMONK_db__user=listmonk
      - LISTMONK_db__password=Attractor-Lifting1-Reminder
      - LISTMONK_db__database=listmonk
      - LISTMONK_db__ssl_mode=disable
#      - TZ=Etc/UTC
      - TZ=Europe/Warsaw
    container_name: listmonk_app
    depends_on:
      - db
    volumes:
      - ./config/config.toml:/listmonk/config.toml
      - ./uploads:/listmonk/uploads
networks:
  listmonk:

volumes:
  listmonk-data:
```
4. config.toml
```
[app]
# Interface and port where the app will run its webserver.  The default value
# of localhost will only listen to connections from the current machine. To
# listen on all interfaces use '0.0.0.0'. To listen on the default web address
# port, use port 80 (this will require running with elevated permissions).
address = "0.0.0.0:9000"

# BasicAuth authentication for the admin dashboard. This will eventually
# be replaced with a better multi-user, role-based authentication system.
# IMPORTANT: Leave both values empty to disable authentication on admin
# only where an external authentication is already setup.
admin_username = "ListAdmin"
admin_password = "Alias-Boned-Chubby3"

# Database.
[db]
host = "db"
port = 5432
user = "listmonk"
password = "Attractor-Lifting1-Reminder"

# Ensure that this database has been created in Postgres.
database = "listmonk"

ssl_mode = "disable"
max_open = 25
max_idle = 25
max_lifetime = "300s"

# Optional space separated Postgres DSN params. eg: "application_name=listmonk gssencmode=disable"
params = ""
```
5. std out:
```
# docker compose up
[+] Building 0.0s (0/0)                                                                                                                                                                                                                        docker:default
[+] Running 2/0
 ✔ Container listmonk_db   Running                                                                                                                                                                                                                       0.0s 
 ✔ Container listmonk_app  Created                                                                                                                                                                                                                       0.0s 
Attaching to listmonk_app, listmonk_db
listmonk_app  | 2023/12/19 15:54:42 main.go:102: v2.5.1 (a6a2b69 2023-08-15T15:49:28Z, linux/amd64)
listmonk_app  | 2023/12/19 15:54:42 init.go:145: reading config: config.toml
listmonk_app  | 2023/12/19 15:54:42 init.go:273: connecting to db: db:5432/listmonk
listmonk_app  | 2023/12/19 15:54:42 init.go:593: media upload provider: filesystem
listmonk_app  | 2023/12/19 15:54:42 init.go:517: loaded email (SMTP) messenger: username@smtp.yoursite.com
listmonk_app  | 2023/12/19 15:54:42 init.go:793: error starting HTTP server: listen tcp: address tcp/9000": unknown port
listmonk_app exited with code 0
listmonk_app  | 2023/12/19 15:54:43 init.go:593: media upload provider: filesystem
listmonk_app  | 2023/12/19 15:54:43 init.go:517: loaded email (SMTP) messenger: username@smtp.yoursite.com
listmonk_app  | 2023/12/19 15:54:43 init.go:793: error starting HTTP server: listen tcp: address tcp/9000": unknown port
listmonk_app exited with code 0
listmonk_app  | 2023/12/19 15:54:44 init.go:593: media upload provider: filesystem
listmonk_app  | 2023/12/19 15:54:44 init.go:517: loaded email (SMTP) messenger: username@smtp.yoursite.com
listmonk_app  | 2023/12/19 15:54:44 init.go:793: error starting HTTP server: listen tcp: address tcp/9000": unknown port
listmonk_app exited with code 1
listmonk_app  | 2023/12/19 15:54:44 init.go:593: media upload provider: filesystem
listmonk_app  | 2023/12/19 15:54:44 init.go:517: loaded email (SMTP) messenger: username@smtp.yoursite.com
listmonk_app  | 2023/12/19 15:54:44 init.go:793: error starting HTTP server: listen tcp: address tcp/9000": unknown port
listmonk_app exited with code 1
listmonk_app  | 2023/12/19 15:54:46 init.go:593: media upload provider: filesystem
listmonk_app  | 2023/12/19 15:54:46 init.go:517: loaded email (SMTP) messenger: username@smtp.yoursite.com
listmonk_app  | 2023/12/19 15:54:46 init.go:793: error starting HTTP server: listen tcp: address tcp/9000": unknown port
listmonk_app exited with code 1
```
