### ISSUE TITLE
Update Docker v2.3.0 to v2.5.1 does not work for me

### ISSUE THREAD

**Issue by manfredu** [knadh/listmonk#1648]
**Version:**
 - listmonk: v2.3.0
 - OS: Ubuntu

**Description of the bug and steps to reproduce:**
I've installed listmonk about a year ago and it's working fine for me. Now I try to upgrade it as described here:
https://github.com/knadh/listmonk/releases/tag/v2.5.1

The messages I get are:
```
# docker-compose run --rm app ./listmonk --upgrade    
Starting listmonk_db ... done    
2024/01/02 02:10:44 main.go:102: v2.5.1 (a6a2b69 2023-08-15T15:49:28Z, linux/amd64)    
2024/01/02 02:10:44 init.go:145: reading config: config.toml    
2024/01/02 02:10:44 init.go:273: connecting to db: localhost:5432/listmonk    
2024/01/02 02:10:44 init.go:277: error connecting to DB: dial tcp 127.0.0.1:5432: connect: connection refused   
``` 

listmonk is not running afterwards. The browser receives code 502

**Configuration:**
config.toml
-------------------------------

```
[app]
address = "0.0.0.0:9000"

admin_username = "admin"
admin_password = "(secret)"

# Database.
[db]
host = "listmonk_db"
port = 5432
user = "listmonk"
password = "(secret)"

# Ensure that this database has been created in Postgres.
database = "listmonk"

ssl_mode = "disable"
max_open = 25
max_idle = 25
max_lifetime = "300s"

# Optional space separated Postgres DSN params. eg: "application_name=listmonk gssencmode=disable"
params = ""
```

docker-compose.yml
--------------------------------
```
version: "3.7"

x-app-defaults: &app-defaults
  restart: unless-stopped
  image: listmonk/listmonk:latest
  ports:
    - "9000:9000"
  networks:
    - listmonk
  environment:
    - TZ=Etc/UTC

x-db-defaults: &db-defaults
  image: postgres:13
  ports:
    - "9432:5432"
  networks:
    - listmonk
  environment:
    - POSTGRES_PASSWORD=(secret)
    - POSTGRES_USER=listmonk
    - POSTGRES_DB=listmonk
  restart: unless-stopped
  healthcheck:
    test: ["CMD-SHELL", "pg_isready -U listmonk"]
    interval: 10s
    timeout: 5s
    retries: 6

services:
  db:
    <<: *db-defaults
    container_name: listmonk_db
    volumes:
      - type: volume
        source: listmonk-data
        target: /var/lib/postgresql/data

  app:
    <<: *app-defaults
    container_name: listmonk_app
    depends_on:
      - db      
    volumes:
      - ./config.toml:/listmonk/config.toml
    volumes:
      - ./uploads:/listmonk/uploads

  demo-db:
    container_name: listmonk_demo_db
    <<: *db-defaults

  demo-app:
    <<: *app-defaults
    container_name: listmonk_demo_app
    command: [sh, -c, "yes | ./listmonk --install --config config-demo.toml && ./listmonk --config config-demo.toml"]
    depends_on:
      - demo-db

networks:
  listmonk:

volumes:
  listmonk-data:
```
