### ISSUE TITLE
Can't get static templates to work with Docker

### ISSUE THREAD

**Issue by poblabs** [knadh/listmonk#1708]
**Version:**
 - listmonk: 2.5.1
 - OS: Ubuntu

I have followed the closed issues here, as well as the documentation and external sites to get the static-dir and static files working, but no matter what it returns a 500 error from listmonk. 

If I remove the file, and restart listmonk, the original template files appear to work. It seems like there's something going on with the templating internals?

---

Docker logs:

```
2024/02/01 18:43:28 main.go:102: v2.5.1 (a6a2b69 2023-08-15T15:49:28Z, linux/amd64)
2024/02/01 18:43:28 init.go:145: reading config: config.toml
2024/02/01 18:43:28 init.go:273: connecting to db: localhost:5432/listmonk
2024/02/01 18:43:28 init.go:232: loading static files from: /listmonk/static/
2024/02/01 18:43:28 init.go:593: media upload provider: filesystem
2024/02/01 18:43:28 init.go:517: loaded email (SMTP) messenger: @email-smtp.us-east-1.amazonaws.com
⇨ http server started on [::]:9000
2024/02/01 18:43:38 handlers.go:62: template: subscription-form.html:15:43: executing "header" at <.AssetVersion>: can't evaluate field AssetVersion in type main.tplData
```

My docker-compose:

```
version: "3.7"

services:
  listmonk:
    restart: unless-stopped
    image: listmonk/listmonk:latest
#    ports:
#      - "127.0.0.1:9000:9000"
    environment:
      - TZ=Etc/New_York
    container_name: listmonk
    volumes:
      - ./config.toml:/listmonk/config.toml
      - ./uploads:/listmonk/uploads/
      - ./static:/listmonk/static
    network_mode: host
#    command: "./listmonk --static-dir=/listmonk/static/"
    command: [sh, -c, "yes | ./listmonk --static-dir=/listmonk/static/"]
```

My tree structure:

```
/docker/listmonk/
├── config.toml
├── docker-compose.yml
├── static
│   ├── email-templates
│   │   ├── base.html
│   │   ├── campaign-status.html
│   │   ├── default-archive.tpl
│   │   ├── default.tpl
│   │   ├── import-status.html
│   │   ├── sample-tx.tpl
│   │   ├── smtp-test.html
│   │   ├── subscriber-data.html
│   │   ├── subscriber-optin-campaign.html
│   │   └── subscriber-optin.html
│   └── public
│       ├── static
│       │   ├── favicon.png
│       │   ├── logo.png
│       │   ├── logo.svg
│       │   ├── rss.svg
│       │   ├── script.js
│       │   └── style.css
│       └── templates
│           ├── archive.html
│           ├── home.html
│           ├── index.html
│           ├── message.html
│           ├── optin.html
│           ├── subscription-form.html
│           └── subscription.html
└── uploads
    ├── download.png
    └── thumb_download.png
```

**Comment by knadh** [comment]
The `master` branch (upcoming release v3.0.0) has changes that are not compatible with v2.5.1. You can pull the templates from the `v2.5.1` tag: https://github.com/knadh/listmonk/tree/v2.5.1

**Comment by panomitrius** [comment]
I had the same problem, and after pulling the templates from the `v2.5.1` tag: [https://github.com/knadh/listmonk/tree/v2.5.1](https://github.com/knadh/listmonk/tree/v2.5.1) the app starts again, but I can't find a way to access the templates in Listmonk. 

This is the relevant parts of my docker-compose.yml

```
  app:
    <<: *app-defaults
    container_name: listmonk_app
    depends_on:
      - db
    command: "./listmonk --static-dir=/listmonk/static"
    volumes:
      - ./config.toml:/listmonk/config.toml
      - ./static:/listmonk/static
```

The files are located on the server that hosts the docker container in ./static with root as owner.

What's wrong?
