### ISSUE TITLE
Connect to Postgres via Unix socket

### ISSUE THREAD

**Issue by areynoua** [knadh/listmonk#1709]
Hello and thank you for the great app.

I'd just like to know if it's possible to configure listmonk to connect to PostgreSQL via a Unix socket rather than TCP. I haven't found any information about this.

Thanks a lot!

**Comment by knadh** [comment]
Setting the `host` param in the config file should work.

```toml
[db]
host = "/var/your/socket"
# ....
```
