### ISSUE TITLE
3.0.0 can't setup webhook for SES/SNS for bounce notification

### ISSUE THREAD

**Issue by poblabs** [knadh/listmonk#1718]
**Version:**
 - listmonk: 3.0.0
 - OS: docker

I'm trying to setup the SES bounce handling and I'm following the docs. When I try to setup SNS with `https://listmonk.yoursite.com/webhooks/service/ses` (and change the domain to my domain) I get a 404 on when browsing it and SNS does not validate it. I am using custom static dir for some template changes I made. When I visit mysite.com/webhooks/service/ses I see my template with the 404. 

Thoughts?

**Comment by MaximilianKohler** [comment]
Is your listmonk site at `domain.com` or `listmonk.domain.com`?

**Comment by poblabs** [comment]
it's at listmonk.domain.com, so i'm trying https://listmonk.domain.com/webhooks/service/ses

**Comment by MaximilianKohler** [comment]
When I browse to `https://listmonk.yoursite.com/webhooks/service/ses` I get a json `message | "Not Found"` page.

So for `I am using custom static dir for some template changes I made. When I visit mysite.com/webhooks/service/ses I see my template with the 404.` you meant `listmonk.yoursite.com/webhooks/service/ses` right?

**Comment by poblabs** [comment]
Ah, sorry. Yes I meant listmonk.yoursite.com/webhooks/service/ses in that sentence. Trying to maintain some domain privacy. 

To be extra clear, when I browse to listmonk.yoursite.com/webhooks/service/ses I get a 404, not a json message. 

I also get a 404 if i restart the docker container without the custom static-dir

**Comment by MaximilianKohler** [comment]
You might have to wait for people who know more than me, but if the home page and /admin pages are working it might be an issue with your nginx or docker config? You should probably post those.

**Comment by poblabs** [comment]
Sure thing:

docker-compose.yml:

```
version: "3.7"

services:
  listmonk:
    restart: unless-stopped
    image: listmonk/listmonk:latest
    environment:
      - TZ=Etc/New_York
    container_name: listmonk
    volumes:
      - ./config.toml:/listmonk/config.toml
      - ./uploads:/listmonk/uploads/
      - ./static:/listmonk/static/
      - ./i18n:/listmonk/i18n/
    network_mode: host
    command: "./listmonk --static-dir=/listmonk/static/ --i18n-dir=/listmonk/i18n"
```

nginx config:

```
server {
    listen 80;
    listen [::]:80;

    # Add index.php to the list if you are using PHP
    index index.php index.html index.htm index.nginx-debian.html;

    server_name listmonk.yoursite.com;

    # Proxy pass for all other requests
    location / {
        proxy_pass http://127.0.0.1:9000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

}
```
