### ISSUE TITLE
502 Gateway Timeout if accessing through proxy

### ISSUE THREAD

**Issue by jmbluethner** [knadh/listmonk#1733]
**Version:**
 - listmonk: 3.0.0
 - OS: Docker on Debian 11

**Description of the bug and steps to reproduce:**

I use <a href="https://nginxproxymanager.com/">Node Proxy Manager</a> to set up all my required proxies. Currently, there are about 20 configured Hosts, almost all of them with Let's Encrypt SSL certs, and all of them are running fine. However, Listmonk gives me a 502.  

The Listmonk application container is exposed on Port 3111. Access via IP:PORT works fine.  nslookup to the domain also gives me the correct IP. The Proxy Manager Log doesn't show any errors.

So, what's the best way of debugging this? The last line in the Listmonk Log is  

`⇨ http server started on [::]:9000`

That looks okay to me. 

Are there any more detailed logs I could dive into?

Edit: For context I'm also adding my docker-compose.yml

```yaml
version: "3.7"

x-app-defaults: &app-defaults
  restart: unless-stopped
  image: listmonk/listmonk:latest
  ports:
    - "3111:9000"
  networks:
    - listmonk
  environment:
    - TZ=Etc/UTC

x-db-defaults: &db-defaults
  image: postgres:13-alpine
  networks:
    - listmonk
  environment:
    - POSTGRES_PASSWORD=XXX
    - POSTGRES_USER=XXX
    - POSTGRES_DB=XXX
  restart: unless-stopped
  healthcheck:
    test: ["CMD-SHELL", "pg_isready -U listmonk"]
    interval: 10s
    timeout: 5s
    retries: 6

services:
  db:
    <<: *db-defaults
    container_name: listmonk_db
    volumes:
      - type: volume
        source: listmonk-data
        target: /var/lib/postgresql/data

  app:
    <<: *app-defaults
    container_name: listmonk_app
    depends_on:
      - db
    links:
      - db
    volumes:
      - ./config.toml:/listmonk/config.toml

networks:
  listmonk:

volumes:
  listmonk-data:
```

Thanks 👋
