### ISSUE TITLE
On saving settings from the dashboard the static directory is not loaded on reload. [Docker]

### ISSUE THREAD

**Issue by adxy** [knadh/listmonk#1737]
**Is your feature request related to a problem? Please describe.**
Since we are loading static dir with a flag which is executed via `docker-compose`, we cannot load static dir if the app restarts via the dashboard. 

This makes it very annoying as we have to go manually restart the app on the server if anyone makes any changes to the settings via the dashboard and the app reloads.  

**Describe the solution you'd like**
I am not sure about this, but one way could be - since the static dir can exist anywhere in the machine and we have to mount the volume to the docker container anyway. Maybe we can move the flag to load static dir to `config.toml`  which can be run on each reload from basically anywhere. 

Example, 

`docker-compose.yml`

```
  app:
    <<: *app-defaults
    depends_on:
      - db    
    volumes:
      - ./config.toml/:/listmonk/config.toml
      - ./your/static/dir:/listmonk/static # map your static dir to default listmonk static dir
```

and `config.toml`
```
[app]
    # Interface and port where the app will run its webserver.
    address = "0.0.0.0:9000"
    admin_username = "listmonk"
    admin_password = "listmonk"

    # we can add something here and if true always display templates from '/listmonk/static' as default static dir
    enable_static_dir = "some_boolean_value"

```

**Comment by MaximilianKohler** [comment]
I think it might be a deficit in your docker-compose.yml file. Can you post your full config?

**Comment by adxy** [comment]
```
version: "3.7"

x-app-defaults: &app-defaults
  restart: unless-stopped
  image: listmonk/listmonk:latest
  ports:
    - "9000:9000"
  networks:
    - listmonk
  environment:
    - TZ=Asia/Kolkata

x-db-defaults: &db-defaults
  image: postgres:13
  ports:
    - "9432:5432"
  networks:
    - listmonk
  environment:
    - POSTGRES_PASSWORD=
    - POSTGRES_USER=listmonk
    - POSTGRES_DB=listmonk
  restart: unless-stopped
  healthcheck:
    test: ["CMD-SHELL", "pg_isready -U listmonk"]
    interval: 10s
    timeout: 5s
    retries: 6

services:
  db:
    <<: *db-defaults
    container_name: listmonk_db
    volumes:
      - type: volume
        source: listmonk-data
        target: /var/lib/postgresql/data

  app:
    <<: *app-defaults
    container_name: listmonk_app
    depends_on:
      - db
    command: "./listmonk --static-dir=/listmonk/static"
    volumes:
      - ./config.toml:/listmonk/config.toml
      - /opt/listmonk-static:/listmonk/static


networks:
  listmonk:

volumes:
  listmonk-data:
```

@MaximilianKohler sorry for the late reply, here's my docker-compose.
