### ISSUE TITLE
Running for multiple domains

### ISSUE THREAD

**Issue by peterbabic** [knadh/listmonk#178]
What is the preferred way to run listmonk for multiple domains on one server?

I have considered these:
1. Have it all in one instance, add SMTP servers for all required domains, change "from" adress respectively
2. Have completely separate Postgres services in docker compose (app1 + db1, app2 + db2, ...)
3. Have only separate app services in docker compose while sharing the DB (app1 + db, app2 + db)

I am not really sure about feasibility of 1. Was able to run 2. without problems, but this creates the most overhead. 

I have tried something like this for 3. but it is not working. Even though there are two separate apps on http://localhost:9001/ and http://localhost:9002/, they share the same DB - it always chooses `listmonk` during `docker-compose run --rm app1 ./listmonk --install`

`** IMPORTANT: This will wipe existing listmonk tables and types in the DB 'listmonk' **`

The `docker-compose.yml` file I have tried for 3.

```yaml
version: "3.7"

x-app-defaults: &app-defaults
  restart: unless-stopped
  image: listmonk/listmonk:latest
  networks:
    - listmonk

x-db-defaults: &db-defaults
    image: postgres:11
    ports:
      - "9432:5432"
    environment:
      - POSTGRES_PASSWORD=listmonk
      - POSTGRES_USER=listmonk
      - POSTGRES_DB=^^^^^^^^^THIS-IS-COMPLETELY-IGNORED^^^^^^^
    networks:
      - listmonk
    volumes:
      - type: volume
        source: listmonk-data
        target: /var/lib/postgresql/data
    restart: unless-stopped

services:
  db:
    <<: *db-defaults

  app1:
    <<: *app-defaults
    ports:
      - "9001:9000"
    depends_on:
      - db
    environment:
      - POSTGRES_DB=listmonk1 # ignored as well

  app2:
    <<: *app-defaults
    ports:
      - "9002:9000"
    depends_on:
      - db
    environment:
      - POSTGRES_DB=listmonk2 # ignored as well

networks:
  listmonk:

volumes:
  listmonk-data:
```

**Comment by knadh** [comment]
> 1) Have it all in one instance, add SMTP servers for all required domains, change "from" adress respectively

We've been running this approach in production. With the new settings UI in v0.7.0, it's easy to toggle SMTP servers for different domains on and off when sending campaigns (along with custom `from` addresses).

@mr-karan could probably comment on the Docker setup.

**Comment by mr-karan** [comment]
> I have tried something like this for 3. but it is not working. Even though there are two separate apps on http://localhost:9001/ and http://localhost:9002/, they share the same DB - it always chooses listmonk during docker-compose run --rm app1 ./listmonk --install

Yep, that's because both the listmonk app instances in your case are connected to the same "database". I'd suggest running 1 as @knadh mentioned with v0.7.0 toggling of SMTPs is really easy.

However if you don't want to do that, you can create a separate DB for each of listmonk and connect to them. You'll need to create the second DB manually and update the config.

There are 2 ways you can go about this (as you mentioned):

-> Write an entrypoint script and mount it like:

```yml
postgres:
  image: postgres:11
  volumes:
    - ./initdb.sql:/docker-entrypoint-initdb.d/init.sql
```

```sql
CREATE DATABASE listmonk1;
CREATE DATABASE listmonk2;
```

So, this script is run everytime Postgres cluster is initialized. 

The second approach, which I think is less maintenance overhead, is to spin up 2 Postgres DB containers one for each listmonk. If you have the resources for it, you can look at this option.
