### ISSUE TITLE
Duble ussage of the same port in the docker-compose file

### ISSUE THREAD

**Issue by nanu-c** [knadh/listmonk#185]
```
x-db-defaults: &db-defaults
    image: postgres:11
    ports:
      - "9432:5432"
```
is also imported in `app: ` so tries to start the db and the app on the same port...
