### ISSUE TITLE
Custom config error: Unsupported config option for services.app: 'volume' (did you mean 'volumes'?)

### ISSUE THREAD

**Issue by GAZ082** [knadh/listmonk#186]
Hi. I'm trying to use my own config.toml. After writing the location as specified in the docs:

```
  app:
    <<: *app-defaults
    depends_on:
      - db
    volume:
    - ./home/myuser/listmonk_docker/config.toml/:/listmonk/config.toml
```
I get when running the composer:
```
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services.app: 'volume' (did you mean 'volumes'?)
```

I double check the identation and stuff to comply with the (annoying) TOML format, no luck. If i replace by volumes it tries to mount the file and throws another error.

What am I doing wrong?

Thanks!

**Comment by mr-karan** [comment]
You should rename `volume` to `volumes` as demonstrated [here](https://github.com/knadh/listmonk/blob/288164ea6a72145183fae14169304d2067997cbc/docker-compose.yml#L30)

**Comment by GAZ082** [comment]
This is when I replace volume by volumes:

```
Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/home/myuser/listmonk_docker/home/myuser/listmonk_docker/config.toml\\\" to rootfs \\\"/var/lib/docker/overlay2/932fb40afcba8d198ad8c539d0e253930eeceb9240bb259f0027c0310798bb16/merged\\\" at \\\"/var/lib/docker/overlay2/932fb40afcba8d198ad8c539d0e253930eeceb9240bb259f0027c0310798bb16/merged/listmonk/config.toml\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
```

**Comment by mr-karan** [comment]
This path looks wrong:

`./home/myuser/listmonk_docker/config.toml`

Can you verify that with 

`cat ./home/myuser/listmonk_docker/config.toml` ?

**Comment by GAZ082** [comment]
With the point the cat did not work, without it did. Originally I did not use the point but wanted to strictly follow the documentation:

https://listmonk.app/docs/installation/#mounting-a-custom-configtoml

Which shows:

```
  app:
    <<: *app-defaults
    depends_on:
      - db
    volume:
    - ./path/on/your/host/config.toml/:/listmonk/config.toml
```

And you can see, there is a point even though it's a file. Perhaps I'm misunderstanding something in docker or the TOML format, i'm alien to both.

**Comment by knadh** [comment]
Can you share the full config file?

> And you can see, there is a point even though it's a file.

If you are referring to "./path", that's just an example. You should replace that with the full path to your config.toml file on disk. The TOML configuration (which is pretty much exactly like INI files) has no relation to do with the Docker file, which is a YAML file.

If you are not familiar with Docker, you may find it easier to follow the non-Docker setup, which involves installing Postgres, downloading the listmonk binary, and running `./listmonk --install`.

**Comment by GAZ082** [comment]
I got it running with the docker configuration. Dont want  the hassle to install the DB and stuff. I just need to run the last mile to be where I want :)

Here is the complete file:

```
version: "3.7"

x-app-defaults: &app-defaults
  restart: unless-stopped
  image: listmonk/listmonk:latest
  ports:
    - "9000:9000"
  networks:
    - listmonk

x-db-defaults: &db-defaults
    image: postgres:11
    ports:
      - "9432:5432"
    networks:
      - listmonk
    environment:
      - POSTGRES_PASSWORD=listmonk
      - POSTGRES_USER=listmonk
      - POSTGRES_DB=listmonk
    restart: unless-stopped

services:
  db:
    <<: *db-defaults
    volumes:
      - type: volume
        source: listmonk-data
        target: /var/lib/postgresql/data

  app:
    <<: *app-defaults
    depends_on:
      - db
    volume:
    - /home/myuser/listmonk_docker/config.toml/:/listmonk/config.toml

networks:
  listmonk:

volumes:
  listmonk-data:
```
