### ISSUE TITLE
No analytics

### ISSUE THREAD

**Issue by liampmccabe** [knadh/listmonk#1864]
**Version:**
 - listmonk: v2.4.0
 - OS: Linux Ubuntu 22.04

**Description of the bug and steps to reproduce:**
I haven't been able to see any analytics for my campaigns. I have subscriber tracking toggled on.
Installed via the [AWS Marketplace](https://aws.amazon.com/marketplace/pp/prodview-jyahcasl6rbg2)

**Screenshots:**
![CleanShot 2024-05-13 at 09 12 21](https://github.com/knadh/listmonk/assets/3018957/3995b3e7-d213-440e-a6ca-6058d772e982)

**Comment by liampmccabe** [comment]
Ah regarding tracking, I see now, from an email noob it's not clear that you have to set up the routes yourself 😅

Also how to retrieve the original URL from the TrackLink URL?

**Comment by liampmccabe** [comment]
I do have one more query, my emails have started to go to spam upon setting the correct root URL and I suspect it's due to the non-ssl ec2 link. I've added a subdomain record but now just need to listmonk to be available on port 443.

Is it just a case of updating the port in the config and restarting docker?

```
version: "3.7"

x-app-defaults: &app-defaults
  restart: unless-stopped
  image: listmonk/listmonk:latest
  ports:
    - "9000:9000"
  networks:
    - listmonk
  environment:
    - TZ=Etc/UTC
```
