### ISSUE TITLE
FEATURE: Docker / K8s - Automatic idempotent install

### ISSUE THREAD

**Issue by Amphaal** [knadh/listmonk#1887]
With something like bool variable that we could set as env to enable / disable this behavior, try to create the database at startup, before trying to running the app.

For now, i need to do something like this to achieve the expected behavior in my K8s deployment manifest:

```
containers:
    - name: listmonk
      image: listmonk/listmonk:latest
      command: ["/bin/sh","-c"]
      args: ["./listmonk --install --yes --idempotent || true && ./listmonk --static-dir={{ listmonk_static_dir }}"]
```

**Comment by knadh** [comment]
Please refer to https://github.com/knadh/listmonk/issues/1852

You can just do this.
```
./listmonk --yes --idempotent --install --upgrade && ./listmonk --static-dir={{ listmonk_static_dir }}"
```

**Comment by Amphaal** [comment]
I did ! 

And now that you bring it, ability to auto-upgrade DB should also be parameterizable along with idempotent. IMO, those behaviors should be enabled by default since this action of setting up / upgrading the DB require absolutely no extra configuration from us. I get that automatic upgrade of tables are always risky, but in-DB backup-like tables may be preferable for optimal UX.

**Comment by knadh** [comment]
> I did !

The `|| true` bit is redundant, right?

Auto-upgrade is very difficult, unfortunately. In a Docker environment, it requires changing the version in the manifest and re-pulling the image.

**Comment by Amphaal** [comment]
`./listmonk --install --yes --idempotent` returns non-zero error code if DB is already setup if I am not mistaken, which will prevent running `./listmonk`, hence the enforced `|| true`.

**Comment by knadh** [comment]
Hi @Amphaal. It doesn't return an error. `--idempotent` is  specifically for that.

**Comment by Amphaal** [comment]
My bad, `./listmonk --install --yes --idempotent` crashed because it was trying to run before DB was ready. Adding an `initContainer` was the trick:
```
      initContainers:
        - name: database-ready
          image: foobic/pg_isready
          env:
            - name: HOST 
              value: <my-db-local-dn>
            - name: RETRIES
              value: "50"
          command: ["/scripts/pg_isready.sh"]

```
