### ISSUE TITLE
Import from Authentik

### ISSUE THREAD

**Issue by Billos** [knadh/listmonk#2157]
An interconnection / import of the subscribers from Authentik backend

**Comment by blahajgoblin** [comment]
@Billos Have you had any success setting that up? I'm looking for the same solution myself right now, and I would really like to omit writing a custom middleware to integrate Authentik with Listmonk.

**Comment by Billos** [comment]
So far I just have a container that queries both APIs, I can share that with you later if you want, but nothing automated, you'd have to run it each time you have a new user

**Comment by Billos** [comment]
```yaml
services:
  import:
    image: alpine:latest
    depends_on:
      listmonk:
        condition: service_healthy
    entrypoint: "/bin/sh -c \"apk add --no-cache curl jq && items=$(curl -H 'Authorization: Bearer XXXXXXXXXXXXXXXXXXX' 'http://authentik:9000/api/v3/core/users/?include_groups=false&ordering=last_login&page=1&page_size=100' \
          | jq -c '.results[] | select(.email != \"\" and .username != \"akadmin\") | {username, name, email}') && \
      for item in \$items; do \
        item_with_status=\$(echo \$item | jq '. + {status: \"enabled\"}') && \
        echo \$item && \
        curl -X POST http://listmonk:9000/api/subscribers -H 'Content-Type: application/json' -d \"$item_with_status\"; \
      done
    \""
```

From what I'm reading, OIDC protocol does not provide a user listing, creating a new middleware would imply to individually implement each existing providers (Authentik, Authelia, Keycloak...)
