### ISSUE TITLE
Slowness loading the webpages

### ISSUE THREAD

**Issue by vderamec** [knadh/listmonk#2196]
**Version:**
 - listmonk: v4.1.0
 - OS: Docker v24.0.7 | docker pull listmonk/listmonk:v4.1.0
 - Web browser: Google Chrome (Version 131.0.6778.109 (Official Build) (arm64))

**Description of the bug and steps to reproduce:**

- Install listmonk using Docker:

```yml
x-db-credentials: &db-credentials                             # Use the default POSTGRES_ credentials if they're available or simply default to "listmonk"
  POSTGRES_USER: &db-user listmonk                            # for database user, password, and database name
  POSTGRES_PASSWORD: &db-password listmonk
  POSTGRES_DB: &db-name listmonk

services:
  # listmonk app
  app:
    image: listmonk/listmonk:latest
    container_name: listmonk_app
    restart: unless-stopped
    ports:
      - "9000:9000"                                           # To change the externally exposed port, change to: $custom_port:9000
    networks:
      - listmonk
    hostname: listmonk.example.com                            # Recommend using FQDN for hostname
    depends_on:
      - db
    command: [sh, -c, "./listmonk --install --idempotent --yes --config '' && ./listmonk --upgrade --yes --config '' && ./listmonk --config ''"]
                                                              # --config (file) param is set to empty so that listmonk only uses the env vars (below) for config.
                                                              # --install --idempotent ensures that DB installation happens only once on an empty DB, on the first ever start.
                                                              # --upgrade automatically runs any DB migrations when a new image is pulled.

    environment:                                              # The same params as in config.toml are passed as env vars here.
      LISTMONK_app__address: 0.0.0.0:9000
      LISTMONK_db__user: *db-user
      LISTMONK_db__password: *db-password
      LISTMONK_db__database: *db-name
      LISTMONK_db__host: listmonk_db
      LISTMONK_db__port: 5432
      LISTMONK_db__ssl_mode: disable
      LISTMONK_db__max_open: 25
      LISTMONK_db__max_idle: 25
      LISTMONK_db__max_lifetime: 300s
      TZ: Etc/UTC
      LISTMONK_ADMIN_USER: ${LISTMONK_ADMIN_USER:-}           # If these (optional) are set during the first `docker compose up`, then the Super Admin user is automatically created.
      LISTMONK_ADMIN_PASSWORD: ${LISTMONK_ADMIN_PASSWORD:-}   # Otherwise, the user can be setup on the web app after the first visit to http://localhost:9000
    volumes:
      - ./uploads:/listmonk/uploads:rw                        # Mount an uploads directory on the host to /listmonk/uploads inside the container.
                                                              # To use this, change directory path in Admin -> Settings -> Media to /listmonk/uploads

  # Postgres database
  db:
    image: postgres:17-alpine
    container_name: listmonk_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    networks:
      - listmonk
    environment:
      <<: *db-credentials
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U listmonk"]
      interval: 10s
      timeout: 5s
      retries: 6
    volumes:
      - type: volume
        source: listmonk-data
        target: /var/lib/postgresql/data

networks:
  listmonk:

volumes:
  listmonk-data:
```

- Then open up listmonk, log in.
- Load the webpages, such as navigating to campaigns and/or subscribers.
- The stylesheets take a very long time to load - about a minute. Each time you change to a webpage, it will take around 1 minute to load. Similarly some javascript files too, such as Subscriber-xxx.js or Campaign-xxxx.js

- Try several times, clearing the cache of your web browser.

**Screenshots:**

- We can see a few "Pending" requests and one custom.css that stopped at 1 minute.
- Most "Pending" network requests will stopped at 1 minute.

![image](https://github.com/user-attachments/assets/659ffe0a-87cf-4bc5-b50e-b1fe1796088b)

![image](https://github.com/user-attachments/assets/f548a83c-74f7-4604-9e2b-22190ff0fb16)
