### ISSUE TITLE
Permit Nesting of Lists

### ISSUE THREAD

**Issue by DinoBellini** [knadh/listmonk#2212]
Example: 

List
KeyUsers-CustomerA: [KU-Subscriber1@CustomerA, KU-Subscriber2@CustomerA, KU-Subscriber3@CustomerA]
KeyUsers-CustomerB: [KU-Subscriber4@CustomerB, KU-Subscriber5@CustomerB]
KeyUsers-CustomerC: [KU-Subscriber6@CustomerC, KU-Subscriber7@CustomerC, KU-Subscriber8@CustomerC]

We need to create a new list: KeyUser-All: [KeyUsers-CustomerA,KeyUsers-CustomerB,KeyUsers-CustomerC]

thks

**Comment by SujithThirumalaisamy** [comment]
## Add `includes` Reference to KeyUser-All List for Simplified Grouping of mailing list
## Description
Currently, we have separate KeyUser lists for customers:

- **KeyUsers-CustomerA:** `[KU-Subscriber1@CustomerA, KU-Subscriber2@CustomerA]`  
- **KeyUsers-CustomerB:** `[KU-Subscriber4@CustomerB, KU-Subscriber5@CustomerB]`

To add this sublist functionality, propose adding an `includes` reference:

```yaml
KeyUser-All:
  users: [SomeOther-CustomerA, SomeOther-CustomerB] // These are included users
  includes: [KeyUsers-CustomerA, KeyUsers-CustomerB] // These are included list
```
Happy to proceed forward to implement these changes both on FE and BE. Happy for any other suggestions on this before getting started
