### ISSUE TITLE
Docker setup: can't change DB port

### ISSUE THREAD

**Issue by mciszczon** [knadh/listmonk#2354]
**Version:**
 - listmonk: `latest` at Docker Hub
 - OS: Mac OS 15.3.2 (24D81)

**Description of the bug and steps to reproduce:**

I cloned the `docker-compose.yml` and the only change I did is to expose the db on a different port. For demonstration purposes, I only changed it from `5432` to `5433`.

The result is that the app is not able to boot up:

```
listmonk_app  | Launching listmonk with user=[root] group=[root] PUID=[0] PGID=[0]
listmonk_app  | 2025/03/17 13:37:48.472653 main.go:107: v4.1.0 (0a27de1 2024-11-12T18:42:26Z, linux/arm64)
listmonk_app  | 2025/03/17 13:37:48.472827 init.go:303: connecting to db: listmonk_db:5433/listmonk
listmonk_app  | 2025/03/17 13:37:48.473457 init.go:307: error connecting to DB: dial tcp 172.18.0.2:5433: connect: connection refused
```

This happens regardless of the port I want to use, but works properly on the default port 5432.
It might be something trivial, but I'm unable to get this working.

Pasting my config here for clarity, but the only two lines that I've changes is the `LISTMONK_db__port` variable, and the `ports` mapping for the DB container.

**docker-compose.yml**

```yaml
x-db-credentials: &db-credentials                             # Use the default POSTGRES_ credentials if they're available or simply default to "listmonk"
  POSTGRES_USER: &db-user listmonk                            # for database user, password, and database name
  POSTGRES_PASSWORD: &db-password listmonk
  POSTGRES_DB: &db-name listmonk

services:
  # listmonk app
  app:
    image: listmonk/listmonk:latest
    container_name: listmonk_app
    restart: unless-stopped
    ports:
      - "9000:9000"                                           # To change the externally exposed port, change to: $custom_port:9000
    networks:
      - listmonk
    hostname: listmonk.example.com                            # Recommend using FQDN for hostname
    depends_on:
      - db
    command: [sh, -c, "./listmonk --install --idempotent --yes --config '' && ./listmonk --upgrade --yes --config '' && ./listmonk --config ''"]
      # --config (file) param is set to empty so that listmonk only uses the env vars (below) for config.
      # --install --idempotent ensures that DB installation happens only once on an empty DB, on the first ever start.
    # --upgrade automatically runs any DB migrations when a new image is pulled.

    environment:                                              # The same params as in config.toml are passed as env vars here.
      LISTMONK_app__address: 0.0.0.0:9000
      LISTMONK_db__user: *db-user
      LISTMONK_db__password: *db-password
      LISTMONK_db__database: *db-name
      LISTMONK_db__host: listmonk_db
      LISTMONK_db__port: 5433
      LISTMONK_db__ssl_mode: disable
      LISTMONK_db__max_open: 25
      LISTMONK_db__max_idle: 25
      LISTMONK_db__max_lifetime: 300s
      TZ: Etc/UTC
      LISTMONK_ADMIN_USER: ${LISTMONK_ADMIN_USER:-}           # If these (optional) are set during the first `docker compose up`, then the Super Admin user is automatically created.
      LISTMONK_ADMIN_PASSWORD: ${LISTMONK_ADMIN_PASSWORD:-}   # Otherwise, the user can be setup on the web app after the first visit to http://localhost:9000
    volumes:
      - ./uploads:/listmonk/uploads:rw                        # Mount an uploads directory on the host to /listmonk/uploads inside the container.
      # To use this, change directory path in Admin -> Settings -> Media to /listmonk/uploads

  # Postgres database
  db:
    image: postgres:17-alpine
    container_name: listmonk_db
    restart: unless-stopped
    ports:
      - "5433:5432"
    networks:
      - listmonk
    environment:
      <<: *db-credentials
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U listmonk"]
      interval: 10s
      timeout: 5s
      retries: 6
    volumes:
      - type: volume
        source: listmonk-data
        target: /var/lib/postgresql/data

networks:
  listmonk:

volumes:
  listmonk-data:
```
