### ISSUE TITLE
Confirmation email not sent for double opt-in lists

### ISSUE THREAD

**Issue by manuscriptory** [knadh/listmonk#2428]
I've been integrating listmonk recently and really enjoying it, thanks for creating such a neat tool!

**Version:**
 - listmonk: v4.1.0
 - OS: Mac, running with Docker

**Description of the bug and steps to reproduce:**
When creating a subscriber either via the UI or the `POST /api/subscribers` API and adding the subscriber to a double opt-in list, no confirmation email is automatically sent. Based on #2276, this is not the intended behaviour.

I can send and receive opt-in emails via the UI's "Send opt-in confirmation" button, plus test (on SMTP page) and transactional emails with no issues (running locally with Mailpit).

There are also no errors appearing in the logs and I haven't found a way to change the log level to debug to confirm a sending attempt.

An example request for a double opt-in list:
```
{
  "email": "email@email.com",
  "name": "Name",
  "status": "enabled",
  "lists": [
    5
  ],
  "attribs": {}
}
```

List configuration:
```
{
    "id": 5,
    "created_at": "2025-04-25T08:44:12.762041Z",
    "updated_at": "2025-04-25T08:44:12.762041Z",
    "uuid": "7b23f8e1-4fd7-48a2-a852-142b2c9fa68a",
    "name": "newsletter",
    "type": "private",
    "optin": "double",
    "tags": [],
    "description": "",
    "subscriber_count": 2,
    "subscriber_statuses": {
        "unconfirmed": 2
    },
    "subscription_created_at": null,
    "subscription_updated_at": null
}
```

Subscriber config after request:
```
{
    "id": 14,
    "created_at": "2025-04-25T08:41:19.131067Z",
    "updated_at": "2025-04-25T09:02:30.609753Z",
    "uuid": "1a3deb0b-94e5-4d46-b2b9-d719c07e28f0",
    "email": "email@email.com",
    "name": "Name",
    "attribs": {},
    "status": "enabled",
    "lists": [
        {
            "subscription_status": "unconfirmed",
            "subscription_created_at": "2025-04-25T09:02:30.609753+00:00",
            "subscription_updated_at": "2025-04-25T09:02:30.609753+00:00",
            "subscription_meta": {},
            "id": 5,
            "uuid": "7b23f8e1-4fd7-48a2-a852-142b2c9fa68a",
            "name": "newsletter",
            "type": "private",
            "optin": "double",
            "tags": null,
            "description": "",
            "created_at": "2025-04-25T08:44:12.762041+00:00",
            "updated_at": "2025-04-25T08:44:12.762041+00:00"
        }
    ]
}
```

I'm running listmonk using Docker with the following compose config:
```
listmonk:
    image: listmonk/listmonk:v4.1.0
    container_name: listmonk
    restart: unless-stopped
    expose:
      - '9000'
    networks:
      - listmonk
    volumes:
      - ./listmonk-static/simontull:/listmonk/static
    command:
      [
        sh,
        -c,
        "./listmonk --install --idempotent --yes --config '' && ./listmonk --upgrade --yes --config '' && ./listmonk --config '' --static-dir=./static",
      ]
      # --config (file) param is set to empty so that listmonk only uses the env vars (below) for config.
      # --install --idempotent ensures that DB installation happens only once on an empty DB, on the first ever start.
      # --upgrade automatically runs any DB migrations when a new image is pulled.
    environment:
      LISTMONK_app__address: 0.0.0.0:9000
      LISTMONK_db__user: listmonkuser
      LISTMONK_db__password: ${DB_PASSWORD:?error}
      LISTMONK_db__database: postgres
      LISTMONK_db__host: ${DB_HOST:?error}
      LISTMONK_db__port: ${DB_PORT:?error}
      LISTMONK_db__ssl_mode: disable
      LISTMONK_db__max_open: 25
      LISTMONK_db__max_idle: 25
      LISTMONK_db__max_lifetime: 300s
      TZ: Melbourne/Australia
      LISTMONK_ADMIN_USER: simon@simontull.com
      LISTMONK_ADMIN_PASSWORD: ${LISTMONK_ADMIN_PASSWORD:?error}
```

**Screenshots:**
Logs after the subscriber is added:
<img width="669" alt="Image" src="https://github.com/user-attachments/assets/fdbd6b28-2788-48b1-a182-008530da79cd" />
