### ISSUE TITLE
Upgrading from v4.1.0 to v5.0.0 breaks Listmonk deployed in Coolify

### ISSUE THREAD

**Issue by lamurian** [knadh/listmonk#2437]
**Version:**
 - listmonk: v.5.0.0
 - OS: Ubuntu

**Description of the bug and steps to reproduce:**
After pulling the latest image, Listmonk fails to re-deploy. I'm deploying Listmonk in Coolify using its pre-configured docker compose:

```
services:
  listmonk:
    image: 'listmonk/listmonk:latest'
    environment:
      - SERVICE_FQDN_LISTMONK_9000
      - 'LISTMONK_app__address=0.0.0.0:9000'
      - LISTMONK_db__host=postgres
      - LISTMONK_db__name=listmonk
      - LISTMONK_db__user=$SERVICE_USER_POSTGRES
      - LISTMONK_db__password=$SERVICE_PASSWORD_POSTGRES
      - LISTMONK_db__port=5432
      - TZ=Etc/UTC
    volumes:
      - 'listmonk-data:/listmonk/uploads'
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test:
        - CMD
        - wget
        - '-q'
        - '--spider'
        - 'http://127.0.0.1:9000'
      interval: 5s
      timeout: 20s
      retries: 10
  listmonk-initial-database-setup:
    image: 'listmonk/listmonk:latest'
    command: './listmonk --install --yes --idempotent'
    restart: 'no'
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - LISTMONK_db__host=postgres
      - LISTMONK_db__name=listmonk
      - LISTMONK_db__user=$SERVICE_USER_POSTGRES
      - LISTMONK_db__password=$SERVICE_PASSWORD_POSTGRES
      - LISTMONK_db__port=5432
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=listmonk
      - POSTGRES_PASSWORD=$SERVICE_PASSWORD_POSTGRES
      - POSTGRES_USER=$SERVICE_USER_POSTGRES
    volumes:
      - 'pg-data:/var/lib/postgresql/data'
    healthcheck:
      test:
        - CMD-SHELL
        - 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}'
      interval: 5s
      timeout: 20s
      retries: 10
```

Logs:

```
2025-04-29T10:21:04.113386996Z Launching listmonk with user=[root] group=[root] PUID=[0] PGID=[0]
2025-04-29T10:21:04.140200029Z 2025/04/29 10:21:04.139650 main.go:106: v5.0.0 (3b8a8c23 2025-04-28T18:51:03Z, linux/amd64)
2025-04-29T10:21:04.140252925Z 2025/04/29 10:21:04.140029 init.go:169: reading config: config.toml
2025-04-29T10:21:04.141566412Z 2025/04/29 10:21:04.140695 init.go:309: connecting to db: postgres:5432/listmonk
2025-04-29T10:21:04.452636422Z 2025/04/29 10:21:04.452472 upgrade.go:111: there are 1 pending database upgrade(s): [v5.0.0]. The last upgrade was v4.1.0. Backup the database and run listmonk --upgrade
```

I take it that I need to run `listmonk --upgrade`, but I'm not sure how to achieve that in Coolify.

**Screenshots:**

Before upgrade:
![Before upgrade](https://github.com/user-attachments/assets/0f2aab25-00b2-4ab3-be05-c67dd100bc43)

After upgrade:
![After upgrade](https://github.com/user-attachments/assets/63107333-c80b-4fdd-b6d5-017fc9c8f8bb)
