### ISSUE TITLE
Disable password login

### ISSUE THREAD

**Issue by ski7777** [knadh/listmonk#2483]
**Is your feature request related to a problem? Please describe.**
We only use OIDC login and do not need password login. For "simple" people two login methods are just causing complications.

**Describe the solution you'd like**
Allow admins to disable password login.

I might implement this on my own. Just for tracking :)

**Comment by knadh** [comment]
You can hide the login form with this snippet (paste it in `Admin -> Settings -> Appearance -> Public -> Custom Javascript`)

```javascript
(() => document.querySelector('section.login div:first-child')?.remove())();
```

**Comment by ski7777** [comment]
Thanks for the tip  👍 

I used CSS instead:
```CSS
section.login>form.form {
    display: none;
}
```

and to disable the password fields in the user management:
```CSS
div.box:has(>.field>label.checkbox>input[name="password_login"]:not(:checked)) {
    display: none;
}
```
Using the `:not(:checked)` the fields stay visible for users with password login but enabling it is not possible :)
