### ISSUE TITLE
docker-compose straight into restarting

### ISSUE THREAD

**Issue by matthewfurr** [knadh/listmonk#37]
I'm using docker-compose to start and stop my containers. As soon as listmonk is starting it has a status of "Restarting (1) Less than a second ago". Logs output something along the lines of

`... main.go:112 reading config config.toml
...main.go:236 error connecting to DB dial tcp lookup demo-db on 127.0.0.11:53 no such host`

I am unable to shell into the container and make adjustments to the config.toml because it is restarting. How should I proceed?

**Comment by knadh** [comment]
listmonk needs to connect to a Postgres database to boot. Have you set that up?

These may be of help:
https://github.com/knadh/listmonk/issues/25#issuecomment-545752512
https://github.com/knadh/listmonk/issues/21#issuecomment-542031723

**Comment by matthewfurr** [comment]
Thanks for the quick response. I have a PostgreSQL database already setup with other services. Based on comment #25, would this be the best way to setup the docker-compose.yml file:

```
version: "3"

networks:
  proxy:
    external: true
  internal:
    external: true

services:
  listmonk:
    image: listmonk/listmonk:latest
    container_name: listmonk
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /home/containers/listmonk/config.toml:./listmonk/config.toml
    networks:
      - proxy
      - internal
    labels:
      - "traefik.enable=true"
      - ...
      - "traefik.docker.network=proxy"
    depends_on:
      - postgres
```

**Comment by mr-karan** [comment]
@matthewfurr You're using `demo-db` in `config.toml` to connect, but since your Postgres service is external, so probably the hostname is different. Use the hostname/port of the existing Postgres and it should work.

Anyway, the docker-compose config is also wrong since you've a `depends_on` field with Postgres but you don't have the Postgres service definition inside docker-compose.

**Comment by matthewfurr** [comment]
@mr-karan, that is correct and that is why I am asking how I can edit the config.toml if the container is always restarting? It goes straight into restarting once it has been started. Therefore, I cannot sh into the container to edit to config.toml and use my Postgres hostname/user/etc... This is why I started this issue.

The docker-compose file is fine. I wouldn't even be able to start the container if it was missing the Postgres service. I didn't think it was necessary to post the entire file with every service I have running. I removed the irrelevant services before posting.

Can you confirm that I have the correct configuration for volumes if I want to make config.toml accessible on my host machine?

**Comment by mr-karan** [comment]
> why I am asking how I can edit the config.toml if the container is always restarting

Since you're mounting the `config.toml` as a `bind` mount, just edit this file locally with correct hostname for postgres and restart the containers.

> cannot sh into the container to edit to config.toml

Yep and that's how it should be. `config` comes as a volume, not something you should change inside when container is running, since you would lose this config the next time container restarts.

>  didn't think it was necessary to post the entire file with every service I have running. I removed the irrelevant services before posting what you see above.

Got it. Since you hadn't mentioned that it's only a portion, I assumed incorrectly.

> Can you confirm that I have the correct configuration for volumes

Yes looks fine, you just need to edit this file from your host machine with correct config.

**Comment by matthewfurr** [comment]
@mr-karan, I haven't been able to successfully create the mount. I got a lot of errors mounting the volumes with my compose file above.

```
    volumes:
      - type: bind
        source: ./listmonk/config.toml
        target: /home/containers/listmonk/settings/config.toml
```
It is still trying to access the same demo database. Thoughts?
