### ISSUE TITLE
Unable to set configuration using full config.toml

### ISSUE THREAD

**Issue by cortopy** [knadh/listmonk#412]
**Version:**
 - listmonk: 1.1.0
 - OS: Docker - Manjaro

**Description of the bug and steps to reproduce:**
I'm trying to configure Listmonk using toml file but most of the values seem to be ignored.

I've transformed the JSON payload for `PUT api/settings` to toml like this:

```toml
[app]
address = "0.0.0.0:9000"
admin_username = "admin"
admin_password = "admin"
batch_size = 1000
check_updates = false
concurrency = 10
enable_public_subscription_page = true
favicon_url = ""
from_email = "My Domain <noreply@example.com>"
lang = "en"
logo_url = "http://localhost:9000/public/static/logo.png"
max_send_errors = 1000
message_rate = 10
message_sliding_window = false
message_sliding_window_duration = "1h"
message_sliding_window_rate = 10000
notify_emails = [ "admin@example.com" ]
root_url = "http://localhost:9000"

[db]
host = "listmonk-db"
port = 5432
user = "listmonk"
password = "listmonk"
database = "listmonk"
ssl_mode = "disable"
max_open = 25
max_idle = 25
max_lifetime = "300s"

[[messengers]]

[privacy]
allow_blocklist = true
allow_export = true
allow_wipe = true
exportable = [ "profile", "subscriptions", "campaign_views", "link_clicks" ]
individual_tracking = false
unsubscribe_header = true

[[smtp]]
auth_protocol = "none"
email_headers = [ ]
enabled = true
hello_hostname = ""
host = "inbucket"
idle_timeout = "15s"
max_conns = 10
max_msg_retries = 2
password = ""
port = 25
strEmailHeaders = "[]"
tls_enabled = false
tls_skip_verify = false
username = ""
uuid = "2f2de335-7675-4d49-b108-fef911102a93"
wait_timeout = "5s"

[[smtp]]
auth_protocol = "plain"
email_headers = [ ]
enabled = false
hello_hostname = ""
host = "smtp2.yoursite.com"
idle_timeout = "15s"
max_conns = 10
max_msg_retries = 2
password = ""
port = 587
strEmailHeaders = "[]"
tls_enabled = false
tls_skip_verify = false
username = "username"
uuid = "4386c82e-e5b0-44b5-a544-7ef9a7fe8f4d"
wait_timeout = "5s"

[upload]
provider = "filesystem"

  [filesystem]
  upload_path = ""
  upload_uri = "/uploads"

  [s3]
  aws_access_key_id = ""
  aws_default_region = "ap-south-b"
  bucket = ""
  bucket_domain = ""
  bucket_path = "/"
  bucket_type = "public"
  expiry = "14d"

```

And then in my docker compose I'm using this command:

```
command:
      [
        sh,
        -c,
        "yes | ./listmonk --install --config config.toml && ./listmonk --config config.toml",
      ]
```

Settings like `admin_password` are recognised and I can login, but others like smtp or `check_updates` are not
