### ISSUE TITLE
Allow credential configuration via environment variables

### ISSUE THREAD

**Issue by NicolaiSchmid** [knadh/listmonk#43]
I think any credentials should be configurable via environment variables. 
I want to deploy listmonk to Kubernetes, I’m creating a Helm chart and I want to leverage a Postgres depedency chart which exposes its password via a secret. I’d like to mount that secret into the listmonk pod via environment-variables.
Also saving the credentials into a secret allows encrypting these values.
If you give me some guidance on code structure I could create a PR request implementing the feature.

**Comment by knadh** [comment]
@NicolaiSchmid listmonk already supports this via [koanf](https://github.com/knadh/koanf). https://github.com/knadh/listmonk/blob/ccd354df3f85259a0b88dffe4a51586aab01135b/main.go#L121

I'll document this. You can pass env config like this:
```
LISTMONK_db__host = "localhost"
LISTMONK_db__password = "xxxx"
```
`LISTMONK_` is the prefix and dots are replaced by double underscore `__`

**Comment by knadh** [comment]
https://github.com/knadh/listmonk/wiki/Developer-setup#configuring-with-environment-variables

**Comment by NicolaiSchmid** [comment]
I could use a little more help, it's getting really confusing. 
I want to set the SMTP configuration. My toml looks like this:
```toml
 # SMTP servers.
    [smtp]
        [smtp.main]
            enabled = true
            host = "host.mail.com"
            port = "587"

            # cram or plain.
            auth_protocol = "plain"
```
and I'm trying to merge the environment like this:
```
LISTMONK_smtp__smtp_main__username
LISTMONK_smtp__smtp_main__password
```

Is that the correct syntax?
Thanks again for your help!
