### ISSUE TITLE
error connecting to DB: pq: password authentication failed for user "listmonk"

### ISSUE THREAD

**Issue by ipflowss** [knadh/listmonk#517]
I am using docker-compose.yml via the install-prod.sh script: sh -c "$(curl -fsSL https://raw.githubusercontent.com/knadh/listmonk/master/install-prod.sh)"

I am getting the following error and not sure how to correct.  I can see the db password in the config.toml and docker-compose.yml file.

```
2021/10/17 23:09:14 main.go:93: v2.0.0 (05585b7 2021-09-27T17:59:39Z)
2021/10/17 23:09:14 init.go:112: reading config: config.toml
2021/10/17 23:09:14 init.go:229: connecting to db: listmonk_db:5432/listmonk
2021/10/17 23:09:14 init.go:232: error connecting to DB: pq: password authentication failed for user "listmonk"
```

```
x-db-defaults: &db-defaults
  image: postgres:13
  ports:
    - "9432:5432"
  networks:
    - listmonk
  environment:
    - POSTGRES_PASSWORD=7nsG2SeOuVjS6
    - POSTGRES_USER=listmonk
    - POSTGRES_DB=listmonk
  restart: unless-stopped
  healthcheck:
    test: ["CMD-SHELL", "pg_isready -U listmonk"]
    interval: 10s
    timeout: 5s
    retries: 6

services:
  db:
    <<: *db-defaults
    container_name: listmonk_db
    volumes:
      - type: volume
        source: listmonk-data
        target: /var/lib/postgresql/data
```

```
# Database.
[db]
host = "listmonk_db"
port = 5432
user = "listmonk"
password = "7nsG2SeOuVjS6"
database = "listmonk"
ssl_mode = "disable"
max_open = 25
max_idle = 25
max_lifetime = "300s"
```
