### ISSUE TITLE
listmonk --install ignores "database" entry in config.toml

### ISSUE THREAD

**Issue by marcin-github** [knadh/listmonk#55]
listmonk --install connects to database with the same name as database user.
version 0.3.3

**Comment by knadh** [comment]
Unable to reproduce this. The DB name is picked up properly.

```toml
# Database.
[db]
host = "localhost"
port = 5432
user = "listmonk"
password = "listmonk"
database = "x"
ssl_mode = "disable"
```

```
2020/02/06 18:24:54 main.go:113: reading config: config.toml
2020/02/06 18:24:54 main.go:236: error connecting to DB: pq: database "x" does not exist
```
