### ISSUE TITLE
Question: How to set up system templates with docker image?

### ISSUE THREAD

**Issue by jwir3** [knadh/listmonk#614]
Hello!

I am using the docker setup, as per the production installation criteria. Can you tell me how I would specify a `static` directory for system overriding system templates?

**Comment by knadh** [comment]
If you're already running listmonk, bring it down by running `docker-compose down app`

Edit docker-compose.yml and change the app section to look like this:
```yaml
  app:
    <<: *app-defaults
    container_name: listmonk_app
    # This new line passes the mounted static-dir to the app.
    command: [sh, -c, "./listmonk --static-dir=/listmonk/static-dir"]
    depends_on:
      - db
    volumes:
      - ./config.toml:/listmonk/config.toml
      # This new line mounts your local static directory in the container.
      - ./path-to-your-your-static-dir-here:/listmonk/static-dir
```
