### ISSUE TITLE
Unable to Change Static Template Files Using Docker

### ISSUE THREAD

**Issue by jpguzman** [knadh/listmonk#747]
Hello!

I installed Listmonk using Docker and it works beautifully. 
However, I want to change the template files, but I am unable to get the --static-dir command working with Docker.

This is the command I was trying:
`docker run --rm listmonk/listmonk:latest ./listmonk --static-dir=static`

The error I am receive is:
```2022/03/15 20:41:04 init.go:127: reading config: config.toml
2022/03/15 20:41:04 init.go:244: connecting to db: localhost:5432/listmonk
2022/03/15 20:41:04 init.go:247: error connecting to DB: dial tcp 127.0.0.1:5432: connect: connection refused
```

I also tried to exec into the docker container and run the ./listmonk --static-dir=static command.
The error when I try that is:
```
2022/03/15 20:45:05 init.go:668: error starting HTTP server: listen tcp 0.0.0.0:9000: bind: address already in use
```

I assume that I am writing the command wrong or I am missing a step.

Question: Can I get a step-by-step guide on how to setup a static directory using Docker?

Thank you!

**Comment by knadh** [comment]
@mr-karan `comamnd: ...` here? https://github.com/knadh/listmonk/blob/9a0f7623b58298543bfad5a32c493ba16bf59313/docker-compose.yml#L45

**Comment by mr-karan** [comment]
@jpguzman You can follow the instructions for mounting a custom config here: https://listmonk.app/docs/installation/#mounting-a-custom-configtoml

(These instructions are for mounting `config.toml`, but should work the same for a static dir too)

You'll need to edit the `docker-compose.yml` to something like:

```yml
  app:
    <<: *app-defaults
    container_name: listmonk_app
    command: ./listmonk --static-dir=/your/custom/path
    depends_on:
      - db
    volumes:
      - /static/path/on/host:/your/custom/path
```

**Comment by jpguzman** [comment]
@mr-karan Thank you! 

This is the config I used to make it work.
Perhaps we can add this to documentation to help others.

In `docker-compose.yml`
```
app:
    <<: *app-defaults
    container_name: listmonk_app
    command: [sh, -c, "yes | ./listmonk --static-dir=./static"]
    depends_on:
      - db
    volumes:
      - ./config.toml:/listmonk/config.toml
      - ./static:/listmonk/static
```

Then I ran: 
`docker-compose up -d app db`
