### ISSUE TITLE
Button Hover Color

### ISSUE THREAD

**Issue by golaat** [knadh/listmonk#753]
How do I adjust the public site button hover color via CSS? 

I can adjust the the button color via the following:
```
.button {
  background-color: #ffb83d; 
}
```
however attempting to override the hover behavior has no effect
```
.button:hover { 
  background-color: #cc9331;
}
```

**Comment by knadh** [comment]
You can try adding `!important`. Eg:

```css
.button:hover { 
  background-color: #cc9331 !important;
}
```
