### ISSUE TITLE
AWS SES SMTP: Error sending test: 451 4.4.2 Timeout waiting for data from client.

### ISSUE THREAD

**Issue by miickel** [knadh/listmonk#81]
When sending emails using AWS SES, we sporadically encounter the error:

`Error sending test: 451 4.4.2 Timeout waiting for data from client.`

How to reproduce:

1. Set up listmonk to use AWS SES:

```toml
[smtp]
    [smtp.ses]
        enabled = true
        host = "email-smtp.eu-west-1.amazonaws.com"
        port = "587"
        auth_protocol = "plain"
        username = "abc"
        password = "xyz"
        send_timeout = 5000
        max_conns = 10
```

2. Create a new campaign.
3. Send a couple of test emails.

It works as expected the first few times you send test emails. But after a few seconds, you get the error message (after hitting send again). Immediately after the error message, if you send another test, it will work a few times more... then the cycle repeats. The same error occurs when sending campaigns, which makes sending email via AWS SES quite unpredictable.

Connecting to AWS from the server is working as expected:

```
~/listmonk$ openssl s_client -crlf -quiet -starttls smtp -connect email-smtp.us-west-2.amazonaws.com:587
depth=2 C = US, O = Amazon, CN = Amazon Root CA 1
verify return:1
depth=1 C = US, O = Amazon, OU = Server CA 1B, CN = Amazon
verify return:1
depth=0 CN = email-smtp.us-west-2.amazonaws.com
verify return:1
250 Ok
```

Other users of AWS SES have been experiencing similar problems when they do not close the connection to the SMTP server after sending the emails, as seen in [this thread on StackOverflow](https://stackoverflow.com/questions/14563200/amazon-ses-stops-working).

When quickly browsing through the listmonk source, I cannot find any calls to [Pool.close()](https://godoc.org/github.com/jordan-wright/email#Pool.Close).

Is it possible to configure listmonk to close and release the connection to the SMTP server once done?

Thanks
