### ISSUE TITLE
Ability to run app with a one liner at any time

### ISSUE THREAD

**Issue by CPLepage** [knadh/listmonk#822]
**Is your feature request related to a problem? Please describe.**
Trying to package listmonk with other services in a docker-compose, but the need to start the db, then the app with --install, then `docker-compose up -d` make everything more complicated. I played around with `--install`, `--idempotent` and `--yes` which brought me to ok results, but a one liner command that install/upgrade if needed and then runs the app through would make it much more easier!

**Describe the solution you'd like**

```yml
  db:
    image: postgres:13
    environment:
      - POSTGRES_PASSWORD=listmonk
      - POSTGRES_USER=listmonk
      - POSTGRES_DB=listmonk
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U listmonk" ]
      interval: 10s
      timeout: 5s
      retries: 6
    volumes:
      - type: volume
        source: listmonk-data
        target: /var/lib/postgresql/data

  app:
    restart: unless-stopped
    image: listmonk/listmonk:latest
    command: ["./listmonk", "--install", "--idempotent", "--yes", "--run-through"]
    ports:
      - "9000:9000"
    environment:
      - TZ=Etc/UTC
    depends_on:
      - db
    volumes:
      - ./config.toml:/listmonk/config.toml
```

If something like this could fresh install in a new environment or simply start if called on `docker-compose restart`, it would be amazing!

**Comment by CPLepage** [comment]
**UPDATE**

use it like this : 
```yml
  app:
    restart: unless-stopped
    image: listmonk/listmonk:latest
    command: /bin/sh -c "./listmonk --install --idempotent --yes && ./listmonk --upgrade --yes && ./listmonk"
    ports:
      - "9000:9000"
    environment:
      - TZ=Etc/UTC
    depends_on:
      - db
    volumes:
      - ./config.toml:/listmonk/config.toml
```
