### ISSUE TITLE
TImeout while running campaign

### ISSUE THREAD

**Issue by L04DB4L4NC3R** [knadh/listmonk#9]
#### System environment
Ubuntu 18.04 LTS

<br>

<details>
<summary> config.toml</summary>

```toml
[app]
# Interface and port where the app will run its webserver.
address = "0.0.0.0:9000"

# Public root URL of the listmonk installation that'll be used
# in the messages for linking to images, unsubscribe page etc.
root = "https://listmonk.mysite.com"

# (Optional) full URL to the static logo to be displayed on
# user facing view such as the unsubscription page.
# eg: https://mysite.com/images/logo.svg
logo_url = ""

# (Optional) full URL to the static favicon to be displayed on
# user facing view such as the unsubscription page.
# eg: https://mysite.com/images/favicon.png
favicon_url = ""

# The default 'from' e-mail for outgoing e-mail campaigns.
from_email = "XXX <XXX@gmail.com>"

# List of e-mail addresses to which admin notifications such as
# import updates, campaign completion, failure etc. should be sent.
# To disable notifications, set an empty list, eg: notify_emails = []
notify_emails = ["XXXXX@gmail.com"]

# Path to the uploads directory where media will be uploaded.
upload_path = "uploads"

# Upload URI that's visible to the outside world. The media
# uploaded to upload_path will be made available publicly
# under this URI, for instance, list.yoursite.com/uploads.
upload_uri = "/uploads"

# Maximum concurrent workers that will attempt to send messages
# simultaneously. This should depend on the number of CPUs the
# machine has and also the number of simultaenous e-mails the
# mail server will
concurrency = 100

# The number of errors (eg: SMTP timeouts while e-mailing) a running
# campaign should tolerate before it is paused for manual
# investigation or intervention. Set to 0 to never pause.
max_send_errors = 1000


# Database.
[db]
host = "demo-db"
port = 5432
user = "listmonk"
password = "listmonk"
database = "listmonk"
ssl_mode = "disable"

# TQekh4quVgGc3HQ


# SMTP servers.
[smtp]
    [smtp.postal]
        enabled = true
        host = "smtp.gmail.com"
        port = "465"

        # cram or plain.
        auth_protocol = "plain"
        username = "XXXXX@gmail.com"
        password = "XXXXX"

        # Maximum time (milliseconds) to wait per e-mail push.
        send_timeout = 5000

        # Maximum concurrent connections to the SMTP server.
        max_conns = 10
```
</details>

<br>

#### Description
- The application timed out while connecting to the SMTP server and no mails were sent. Subsequently, the campaign status changed to `finished`.

- Tried it with `OAuth2` authentication mechanism for the SMTP server but didn't Plain mechanism is being used for all other auth methods (other than cram)

<br>

#### Likely issue
`plain` authenticaiton mechanism is being used in case of auth auth mechanisms other than `cram`.
https://github.com/knadh/listmonk/blob/180f05ac081f6f73b0df48e5a046f996dbc97a88/messenger/emailer.go#L41
