### ISSUE TITLE
Cannot change the system templates

### ISSUE THREAD

**Issue by davidahmed** [knadh/listmonk#941]
I have an instance of Listmonk (docker) installed with everything being functional except the system templates.

Following the documentation [here](https://listmonk.app/docs/templating/#system-templates) here, I run my listmonk instance with the following flag `./listmonk --static-dir=my/custom/path`

Here's the relevant section of the docker-compose.yml file
```yml
  app: 
    <<: *app-defaults 
    container_name: listmonk_app 
    depends_on: 
      - db 
    command: [sh, -c, "./listmonk --config config.toml --static-dir=/static/"] 
    volumes: 
      - ./config.toml:/listmonk/config.toml 
      - ./uploads/:/listmonk/uploads 
      - ./static/:/static/ 
```
According to the listmonk logs, the `static` folder for templates is working too.

```bash
2022/09/10 21:27:04 v2.2.0 (bbbf28c 2022-07-30T18:18:24Z)
2022/09/10 21:27:04 reading config: config.toml
2022/09/10 21:27:04 connecting to db: listmonk_db:5432/listmonk
2022/09/10 21:27:04 loading static files from: /static/
2022/09/10 21:27:04 media upload provider: filesystem
```
However, I have tried changing the files:
`static/email-templates/base.html` -> but it doesn't affect any of the email sent out.
`static/public/templates/index.html` -> but it dones't affect any of the public pages.

What am I missing?

**Comment by davidahmed** [comment]
Hmm interestingly enough, I followed this issue (https://github.com/knadh/listmonk/issues/747) and my issue is resolved too. I will leave the issue open (in case someone can explain what I was doing wrong); otherwise the issue may be closed.

**Comment by davidahmed** [comment]
Here's what I used to solve the issue:
```yml
  app:
    <<: *app-defaults
    container_name: listmonk_app
    depends_on:
      - db
    command: [sh, -c, "yes | ./listmonk --static-dir=./static/"]
    volumes:
      - ./config.toml:/listmonk/config.toml
      - ./uploads/:/listmonk/uploads
      - ./static/:/listmonk/static
```

**Comment by knadh** [comment]
@mr-karan is there something we should update in the docs?

**Comment by mr-karan** [comment]
The docs seem fine. 

@davidahmed I am not able to reproduce this issue:

![image](https://user-images.githubusercontent.com/5689132/189584454-9af0118e-598f-4c07-aaa5-6bbfd24d9f84.png)


```
  demo-app:
    <<: *app-defaults
    container_name: listmonk_demo_app
    command: [sh, -c, "yes | ./listmonk --install --config config-demo.toml && ./listmonk --config config-demo.toml --static-dir=/static/"]
    depends_on:
      - demo-db
    volumes:
      - ./static/:/static
```

I changed `static/public/templates/index.html` and the changes do seem to reflect correctly.
